[pickle]
file_path = "dt_model.pkl"

[training]
columns = ['domain_token_count', 'avgpathtokenlen', 'urlLen', 'domainlength',
       'ArgUrlRatio', 'NumberofDotsinURL', 'URL_DigitCount',
       'Filename_LetterCount', 'LongestPathTokenLength',
       'Path_LongestWordLength', 'spcharUrl', 'NumberRate_Domain',
       'Entropy_Domain']